name: CI with Slack Alerts

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: echo "Build running..."

      - name: Slack Success Notification
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Build Passed 🚀"}' \
          ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Failure Notification
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Build Failed 🔥"}' \
          ${{ secrets.SLACK_WEBHOOK }}